### PR TITLE
Add .nojekyll file to bypass Jekyll part of build

### PR DESCRIPTION
**Pull request by wojsmol**

### CODE REVIEW

**Review by danielbachhuber — APPROVED** [review]
Thanks!

**Comment by danielbachhuber** [comment]
@wojsmol Looks like there's something else broken:

CleanShot 2023-10-26 at 16 14 32@2x

**Comment by szepeviktor** [comment]
That is a symlink.
https://github.com/wp-cli/builds/blob/gh-pages/deb/php-wpcli_latest_all.deb

**Comment by szepeviktor** [comment]
.... and that is a problem ⚡ 

https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#troubleshooting-publishing-from-a-branch

> [!NOTE]
> If your repository contains symbolic links, you will need to publish your site using a GitHub Actions workflow. For more information about GitHub Actions, see "[GitHub Actions documentation](https://docs.github.com/en/actions)."

**Pull request merged**
