### PR TITLE
Added v0.21.1 and v0.20.4

### PR DESCRIPTION
**Pull request by szepeviktor**
Fixes: #29

Please help in #30

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@szepeviktor merge conflict, which means your `master` probably isn't up to date

**Comment by szepeviktor** [comment]
Both of theme are here.
No guaranties for 0.20.4!

**Comment by danielbachhuber** [comment]
@szepeviktor there's still a merge conflict

**Comment by szepeviktor** [comment]
Excuse me.

**Pull request merged**
