### PR TITLE
Adds the php-wpcli 0.14.0 package.

### PR DESCRIPTION
**Pull request by tiagohillebrandt**

### CODE REVIEW

**Comment by scribu** [comment]
Hi, can you also provide the script that generated this package? Or at least the source files?

**Comment by tiagohillebrandt** [comment]
Hey scribu, I have generated this package manually using debuild.

Here are the source files: https://github.com/tiagohillebrandt/wp-cli-deb

Also, if you prefer you can extract the deb package and check the content integrity.

**Comment by scribu** [comment]
Thanks!

**Comment by tiagohillebrandt** [comment]
Hey, thanks for the merge. I am planning to maintain the deb files for next releases too.

**Comment by scribu** [comment]
That would be great! I've added a section on this [wiki page](https://github.com/wp-cli/wp-cli/wiki/Alternative-Install-Methods#wiki-installing-via-deb-package) but feel free to expand it.

**Pull request merged**
